apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-crud-k8s
          image: 01112021/react-springboot-mysql-stack
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
          env:   # Setting Enviornmental Variables
            - name: DB_URL   # Setting Database host address from configMap
              value: mysql
            - name: DB_USERNAME  # Setting Database name from configMap
              value: admin
            - name: DB_NAME  # Setting Database username from Secret
              value: fullstack
            - name: DB_PASSWORD # Setting Database password from Secret
              value: password
            - name: FRONTEND_ENDPOINT # Setting Database password from Secret
              value:http://13.235.31.106:8181

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.
